"""Add reference_image_uris

Revision ID: 3f709d6b793d
Revises: 6591e10bbab7
Create Date: 2026-01-12 14:31:58.559822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f709d6b793d'
down_revision: Union[str, None] = '6591e10bbab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_guidelines', sa.Column('reference_image_uris', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_guidelines', 'reference_image_uris')
    # ### end Alembic commands ###
