"""add session_id to storyboard

Revision ID: 8493cfe9111e
Revises: ae0287db1562
Create Date: 2026-04-12 23:47:59.272855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8493cfe9111e'
down_revision: Union[str, None] = 'ae0287db1562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboards', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storyboards', 'session_id')
    # ### end Alembic commands ###
